[package]
name = "micron_environment"
version = "0.1.0"
authors = ["bosley <bosley117@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = { version="0.19.0", features = ["lexer"] }

[dependencies]
rug = "1.11.0"
derive_more = "0.99.0"

micron_ast = { path = "../ast" }